### PR TITLE
[WIP] Spherical Terrain

### PR DESCRIPTION
**Pull request by kurtkuehnert**
A WIP implementation of spherical terrain.
This will be in a prototype stage for a couple of weeks.

### CODE REVIEW

**Comment by kurtkuehnert** [comment]
Screenshot 2023-10-19 152248
Screenshot 2023-10-19 152732

Both planar and spherical terrains use the same implementation now. You can enable the latter using the cargo "spherical" feature.

I have also experimented with an early attempt at mapping a cube map to the planet.

**Comment by kurtkuehnert** [comment]
Screenshot 2023-10-21 112740

**Comment by spectrachrome** [comment]
What terrain data do you use in the spherical terrain example? I'm always getting a "No such file or directory" error and adding the six 32K tiles also seems to be the wrong approach.

Amazing work so far! 🙌

**Comment by kurtkuehnert** [comment]
@spectrachrome 

Thank you. This PR is quite a big overhaul and constantly changing. I would not depend on it so far. I hope to get the plugin in a usable state again by early next year.

I have not added the large textures to git, to avoid bloating the repo.
I will make a smaller dataset for testing, once the rest is cleaned up.

**Pull request merged**
